services:
  server:
    build: ./server
    container_name: studygenie-server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  client:
    build: ./client
    container_name: studygenie-client
    ports:
      - "3000:3000"
    depends_on:
      - server